
parameters:
  name: ''
  vmImage: ''
  matrix: []

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  variables:
    - group: AWS_CREDENTIALS
    - name: VIRTUALENV
      value: 'testvenv'
    - name: JUNITXML
      value: 'test-data.xml'
    - name: TMP_FOLDER
      value: '$(Agent.WorkFolder)\tmp_folder'
  strategy:
    matrix:
      ${{ insert }}: ${{ parameters.matrix }}

  steps:
    - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
      displayName: Add conda to PATH for 64 bit Python
    - script: |
        ci\\azure\\install.cmd
      displayName: 'Install'
    - script: |
        ci\\azure\\test_rust.cmd
      displayName: 'Test rust'
    - script: |
        ci\\azure\\test_python.cmd
      displayName: 'Test python'
    - script: |
        ci\\azure\\upload_wheels.cmd
      displayName: 'Upload wheels'
      env:
         AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
         AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: "${{ parameters.name }}-$(PYTHON_VERSION)-wheels"
        targetPath: python\\dist\\
